name: Build and Push Go Application

on: 
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v8,linux/arm64/v8
          push: true
          tags: johnjohnofficial/http-wait:$GITHUB_SHA

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./Dockerfile
          push: true
          tags: johnjohnofficial/http-wait:$GITHUB_SHA, johnjohnofficial/http-wait:latest
