name: Build and Push Go Application

on: 
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build for linux/amd64
        run: |
          docker buildx build --platform linux/amd64 -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$GITHUB_SHA .
          docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$GITHUB_SHA
      - name: Build for linux/arm/v8
        run: |
          docker buildx build --platform linux/arm/v8 -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$GITHUB_SHA .
          docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$GITHUB_SHA
      - name: Build for linux/arm64/v8
        run: |
          docker buildx build --platform linux/arm64/v8 -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$GITHUB_SHA .
          docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$GITHUB_SHA
      - name: Push to Docker Hub
        run: |
          docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$GITHUB_SHA
          docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest
